
package se.ledningskollen.api.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AuthenticateWebServiceUserSoap", targetNamespace = "http://ella.ledningskollen.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticateWebServiceUserSoap {


    /**
     * 
     * @param userName
     * @param passWord
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Login", action = "http://ella.ledningskollen.se/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.login.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.login.LoginResponse")
    public String login(
        @WebParam(name = "userName", targetNamespace = "http://ella.ledningskollen.se/")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "http://ella.ledningskollen.se/")
        String passWord);

    /**
     * 
     * @param asUser
     * @param username
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LoginAsUser", action = "http://ella.ledningskollen.se/LoginAsUser")
    @WebResult(name = "LoginAsUserResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "LoginAsUser", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.login.LoginAsUser")
    @ResponseWrapper(localName = "LoginAsUserResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.login.LoginAsUserResponse")
    public String loginAsUser(
        @WebParam(name = "username", targetNamespace = "http://ella.ledningskollen.se/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://ella.ledningskollen.se/")
        String password,
        @WebParam(name = "asUser", targetNamespace = "http://ella.ledningskollen.se/")
        String asUser);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LogOut", action = "http://ella.ledningskollen.se/LogOut")
    @WebResult(name = "LogOutResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "LogOut", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.login.LogOut")
    @ResponseWrapper(localName = "LogOutResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.login.LogOutResponse")
    public String logOut();

}
