
package se.ledningskollen.api.login;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthenticateWebServiceUser", targetNamespace = "http://ella.ledningskollen.se/", wsdlLocation = "https://ella.ledningskollen.se/cableowner/Login.asmx?wsdl")
public class AuthenticateWebServiceUser
    extends Service
{

    private final static URL AUTHENTICATEWEBSERVICEUSER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(se.ledningskollen.api.login.AuthenticateWebServiceUser.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = se.ledningskollen.api.login.AuthenticateWebServiceUser.class.getResource(".");
            url = new URL(baseUrl, "https://ella.ledningskollen.se/cableowner/Login.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://ella.ledningskollen.se/cableowner/Login.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTHENTICATEWEBSERVICEUSER_WSDL_LOCATION = url;
    }

    public AuthenticateWebServiceUser(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticateWebServiceUser() {
        super(AUTHENTICATEWEBSERVICEUSER_WSDL_LOCATION, new QName("http://ella.ledningskollen.se/", "AuthenticateWebServiceUser"));
    }

    /**
     * 
     * @return
     *     returns AuthenticateWebServiceUserSoap
     */
    @WebEndpoint(name = "AuthenticateWebServiceUserSoap")
    public AuthenticateWebServiceUserSoap getAuthenticateWebServiceUserSoap() {
        return super.getPort(new QName("http://ella.ledningskollen.se/", "AuthenticateWebServiceUserSoap"), AuthenticateWebServiceUserSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticateWebServiceUserSoap
     */
    @WebEndpoint(name = "AuthenticateWebServiceUserSoap")
    public AuthenticateWebServiceUserSoap getAuthenticateWebServiceUserSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ella.ledningskollen.se/", "AuthenticateWebServiceUserSoap"), AuthenticateWebServiceUserSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticateWebServiceUserSoap
     */
    @WebEndpoint(name = "AuthenticateWebServiceUserSoap12")
    public AuthenticateWebServiceUserSoap getAuthenticateWebServiceUserSoap12() {
        return super.getPort(new QName("http://ella.ledningskollen.se/", "AuthenticateWebServiceUserSoap12"), AuthenticateWebServiceUserSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticateWebServiceUserSoap
     */
    @WebEndpoint(name = "AuthenticateWebServiceUserSoap12")
    public AuthenticateWebServiceUserSoap getAuthenticateWebServiceUserSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ella.ledningskollen.se/", "AuthenticateWebServiceUserSoap12"), AuthenticateWebServiceUserSoap.class, features);
    }

}
