
package se.ledningskollen.api.cableowner;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CableOwnerSoap", targetNamespace = "http://ella.ledningskollen.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CableOwnerSoap {


    /**
     * 
     * @param aoi
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddAreaOfInterest", action = "http://ella.ledningskollen.se/AddAreaOfInterest")
    @WebResult(name = "AddAreaOfInterestResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "AddAreaOfInterest", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.AddAreaOfInterest")
    @ResponseWrapper(localName = "AddAreaOfInterestResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.AddAreaOfInterestResponse")
    public String addAreaOfInterest(
        @WebParam(name = "aoi", targetNamespace = "http://ella.ledningskollen.se/")
        AreaOfInterest aoi);

    /**
     * 
     * @param aoiId
     * @param geometry
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddGeometryToAreaOfInterest", action = "http://ella.ledningskollen.se/AddGeometryToAreaOfInterest")
    @WebResult(name = "AddGeometryToAreaOfInterestResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "AddGeometryToAreaOfInterest", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.AddGeometryToAreaOfInterest")
    @ResponseWrapper(localName = "AddGeometryToAreaOfInterestResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.AddGeometryToAreaOfInterestResponse")
    public String addGeometryToAreaOfInterest(
        @WebParam(name = "aoiId", targetNamespace = "http://ella.ledningskollen.se/")
        int aoiId,
        @WebParam(name = "geometry", targetNamespace = "http://ella.ledningskollen.se/")
        Geometry geometry);

    /**
     * 
     * @param aoiId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteAreaOfInterest", action = "http://ella.ledningskollen.se/DeleteAreaOfInterest")
    @WebResult(name = "DeleteAreaOfInterestResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "DeleteAreaOfInterest", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.DeleteAreaOfInterest")
    @ResponseWrapper(localName = "DeleteAreaOfInterestResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.DeleteAreaOfInterestResponse")
    public String deleteAreaOfInterest(
        @WebParam(name = "aoiId", targetNamespace = "http://ella.ledningskollen.se/")
        int aoiId);

    /**
     * 
     * @param name
     * @param aoiId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EditAreaOfInterest", action = "http://ella.ledningskollen.se/EditAreaOfInterest")
    @WebResult(name = "EditAreaOfInterestResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "EditAreaOfInterest", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.EditAreaOfInterest")
    @ResponseWrapper(localName = "EditAreaOfInterestResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.EditAreaOfInterestResponse")
    public String editAreaOfInterest(
        @WebParam(name = "aoiId", targetNamespace = "http://ella.ledningskollen.se/")
        int aoiId,
        @WebParam(name = "name", targetNamespace = "http://ella.ledningskollen.se/")
        String name);

    /**
     * 
     * @param geometryId
     * @param aoiId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteGeometriesFromAreaOfInterest", action = "http://ella.ledningskollen.se/DeleteGeometriesFromAreaOfInterest")
    @WebResult(name = "DeleteGeometriesFromAreaOfInterestResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "DeleteGeometriesFromAreaOfInterest", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.DeleteGeometriesFromAreaOfInterest")
    @ResponseWrapper(localName = "DeleteGeometriesFromAreaOfInterestResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.DeleteGeometriesFromAreaOfInterestResponse")
    public String deleteGeometriesFromAreaOfInterest(
        @WebParam(name = "aoiId", targetNamespace = "http://ella.ledningskollen.se/")
        int aoiId,
        @WebParam(name = "geometryId", targetNamespace = "http://ella.ledningskollen.se/")
        int geometryId);

    /**
     * 
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfAreaOfInterest1
     */
    @WebMethod(operationName = "GetAllAreasOfInterestWithData", action = "http://ella.ledningskollen.se/GetAllAreasOfInterestWithData")
    @WebResult(name = "GetAllAreasOfInterestWithDataResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetAllAreasOfInterestWithData", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetAllAreasOfInterestWithData")
    @ResponseWrapper(localName = "GetAllAreasOfInterestWithDataResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetAllAreasOfInterestWithDataResponse")
    public ArrayOfAreaOfInterest1 getAllAreasOfInterestWithData();

    /**
     * 
     * @param aoiId
     * @return
     *     returns se.ledningskollen.api.cableowner.AreaOfInterest1
     */
    @WebMethod(operationName = "GetAreaOfInterest", action = "http://ella.ledningskollen.se/GetAreaOfInterest")
    @WebResult(name = "GetAreaOfInterestResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetAreaOfInterest", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetAreaOfInterest")
    @ResponseWrapper(localName = "GetAreaOfInterestResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetAreaOfInterestResponse")
    public AreaOfInterest1 getAreaOfInterest(
        @WebParam(name = "aoiId", targetNamespace = "http://ella.ledningskollen.se/")
        int aoiId);

    /**
     * 
     * @param caseNumber
     * @return
     *     returns se.ledningskollen.api.cableowner.Case
     */
    @WebMethod(operationName = "GetCase", action = "http://ella.ledningskollen.se/GetCase")
    @WebResult(name = "GetCaseResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetCase", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetCase")
    @ResponseWrapper(localName = "GetCaseResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetCaseResponse")
    public Case getCase(
        @WebParam(name = "caseNumber", targetNamespace = "http://ella.ledningskollen.se/")
        String caseNumber);

    /**
     * This method will be deprecated. Use GetCasesWhichRequireManualReview instead
     * 
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfCase
     */
    @WebMethod(operationName = "GetAllCases", action = "http://ella.ledningskollen.se/GetAllCases")
    @WebResult(name = "GetAllCasesResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetAllCases", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetAllCases")
    @ResponseWrapper(localName = "GetAllCasesResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetAllCasesResponse")
    public ArrayOfCase getAllCases();

    /**
     * 
     * @param recipients
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfCase
     */
    @WebMethod(operationName = "GetCasesWhichRequireManualReview", action = "http://ella.ledningskollen.se/GetCasesWhichRequireManualReview")
    @WebResult(name = "GetCasesWhichRequireManualReviewResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetCasesWhichRequireManualReview", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetCasesWhichRequireManualReview")
    @ResponseWrapper(localName = "GetCasesWhichRequireManualReviewResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetCasesWhichRequireManualReviewResponse")
    public ArrayOfCase getCasesWhichRequireManualReview(
        @WebParam(name = "recipients", targetNamespace = "http://ella.ledningskollen.se/")
        ArrayOfRecipient recipients);

    /**
     * 
     * @param caseNumber
     */
    @WebMethod(operationName = "SetCaseAsFetched", action = "http://ella.ledningskollen.se/SetCaseAsFetched")
    @RequestWrapper(localName = "SetCaseAsFetched", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.SetCaseAsFetched")
    @ResponseWrapper(localName = "SetCaseAsFetchedResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.SetCaseAsFetchedResponse")
    public void setCaseAsFetched(
        @WebParam(name = "caseNumber", targetNamespace = "http://ella.ledningskollen.se/")
        String caseNumber);

    /**
     * 
     * @param caseNumber
     */
    @WebMethod(operationName = "CaseRequiresManualReview", action = "http://ella.ledningskollen.se/CaseRequiresManualReview")
    @RequestWrapper(localName = "CaseRequiresManualReview", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.CaseRequiresManualReview")
    @ResponseWrapper(localName = "CaseRequiresManualReviewResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.CaseRequiresManualReviewResponse")
    public void caseRequiresManualReview(
        @WebParam(name = "caseNumber", targetNamespace = "http://ella.ledningskollen.se/")
        String caseNumber);

    /**
     * 
     * @param creationEndDate
     * @param includePreliminary
     * @param inquirer
     * @param includeFetchedCases
     * @param creationStartDate
     * @param cableOwner
     * @param includeClosed
     * @param workStartDate
     * @param includeOpen
     * @param workEndDate
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfCase
     */
    @WebMethod(operationName = "GetFilteredCaseListWithStatus", action = "http://ella.ledningskollen.se/GetFilteredCaseListWithStatus")
    @WebResult(name = "GetFilteredCaseListWithStatusResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetFilteredCaseListWithStatus", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetFilteredCaseListWithStatus")
    @ResponseWrapper(localName = "GetFilteredCaseListWithStatusResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetFilteredCaseListWithStatusResponse")
    public ArrayOfCase getFilteredCaseListWithStatus(
        @WebParam(name = "includeOpen", targetNamespace = "http://ella.ledningskollen.se/")
        boolean includeOpen,
        @WebParam(name = "includeClosed", targetNamespace = "http://ella.ledningskollen.se/")
        boolean includeClosed,
        @WebParam(name = "includePreliminary", targetNamespace = "http://ella.ledningskollen.se/")
        boolean includePreliminary,
        @WebParam(name = "cableOwner", targetNamespace = "http://ella.ledningskollen.se/")
        String cableOwner,
        @WebParam(name = "inquirer", targetNamespace = "http://ella.ledningskollen.se/")
        String inquirer,
        @WebParam(name = "creationStartDate", targetNamespace = "http://ella.ledningskollen.se/")
        String creationStartDate,
        @WebParam(name = "creationEndDate", targetNamespace = "http://ella.ledningskollen.se/")
        String creationEndDate,
        @WebParam(name = "workStartDate", targetNamespace = "http://ella.ledningskollen.se/")
        String workStartDate,
        @WebParam(name = "workEndDate", targetNamespace = "http://ella.ledningskollen.se/")
        String workEndDate,
        @WebParam(name = "includeFetchedCases", targetNamespace = "http://ella.ledningskollen.se/")
        boolean includeFetchedCases);

    /**
     * 
     * @param creationEndDate
     * @param includePreliminary
     * @param inquirer
     * @param creationStartDate
     * @param cableOwner
     * @param includeClosed
     * @param workStartDate
     * @param includeOpen
     * @param workEndDate
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfCase
     */
    @WebMethod(operationName = "GetFilteredCaseList", action = "http://ella.ledningskollen.se/GetFilteredCaseList")
    @WebResult(name = "GetFilteredCaseListResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetFilteredCaseList", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetFilteredCaseList")
    @ResponseWrapper(localName = "GetFilteredCaseListResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetFilteredCaseListResponse")
    public ArrayOfCase getFilteredCaseList(
        @WebParam(name = "includeOpen", targetNamespace = "http://ella.ledningskollen.se/")
        boolean includeOpen,
        @WebParam(name = "includeClosed", targetNamespace = "http://ella.ledningskollen.se/")
        boolean includeClosed,
        @WebParam(name = "includePreliminary", targetNamespace = "http://ella.ledningskollen.se/")
        boolean includePreliminary,
        @WebParam(name = "cableOwner", targetNamespace = "http://ella.ledningskollen.se/")
        String cableOwner,
        @WebParam(name = "inquirer", targetNamespace = "http://ella.ledningskollen.se/")
        String inquirer,
        @WebParam(name = "creationStartDate", targetNamespace = "http://ella.ledningskollen.se/")
        String creationStartDate,
        @WebParam(name = "creationEndDate", targetNamespace = "http://ella.ledningskollen.se/")
        String creationEndDate,
        @WebParam(name = "workStartDate", targetNamespace = "http://ella.ledningskollen.se/")
        String workStartDate,
        @WebParam(name = "workEndDate", targetNamespace = "http://ella.ledningskollen.se/")
        String workEndDate);

    /**
     * 
     * @param caseNumber
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsCaseCanceled", action = "http://ella.ledningskollen.se/IsCaseCanceled")
    @WebResult(name = "IsCaseCanceledResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "IsCaseCanceled", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.IsCaseCanceled")
    @ResponseWrapper(localName = "IsCaseCanceledResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.IsCaseCanceledResponse")
    public boolean isCaseCanceled(
        @WebParam(name = "caseNumber", targetNamespace = "http://ella.ledningskollen.se/")
        String caseNumber);

    /**
     * 
     * @param measures
     * @param comment
     * @param caseNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConfirmCase", action = "http://ella.ledningskollen.se/ConfirmCase")
    @WebResult(name = "ConfirmCaseResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "ConfirmCase", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.ConfirmCase")
    @ResponseWrapper(localName = "ConfirmCaseResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.ConfirmCaseResponse")
    public String confirmCase(
        @WebParam(name = "caseNumber", targetNamespace = "http://ella.ledningskollen.se/")
        String caseNumber,
        @WebParam(name = "comment", targetNamespace = "http://ella.ledningskollen.se/")
        String comment,
        @WebParam(name = "measures", targetNamespace = "http://ella.ledningskollen.se/")
        ArrayOfMeasure measures);

    /**
     * 
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfRecipient
     */
    @WebMethod(operationName = "GetRecipients", action = "http://ella.ledningskollen.se/GetRecipients")
    @WebResult(name = "GetRecipientsResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetRecipients", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetRecipients")
    @ResponseWrapper(localName = "GetRecipientsResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetRecipientsResponse")
    public ArrayOfRecipient getRecipients();

    /**
     * 
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfPurpose
     */
    @WebMethod(operationName = "GetPurposes", action = "http://ella.ledningskollen.se/GetPurposes")
    @WebResult(name = "GetPurposesResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetPurposes", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetPurposes")
    @ResponseWrapper(localName = "GetPurposesResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetPurposesResponse")
    public ArrayOfPurpose getPurposes();

    /**
     * 
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfMeasure
     */
    @WebMethod(operationName = "GetMeasures", action = "http://ella.ledningskollen.se/GetMeasures")
    @WebResult(name = "GetMeasuresResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetMeasures", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetMeasures")
    @ResponseWrapper(localName = "GetMeasuresResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetMeasuresResponse")
    public ArrayOfMeasure getMeasures();

    /**
     * 
     * @param purpose
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfMeasure
     */
    @WebMethod(operationName = "GetMeasuresForPurpose", action = "http://ella.ledningskollen.se/GetMeasuresForPurpose")
    @WebResult(name = "GetMeasuresForPurposeResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetMeasuresForPurpose", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetMeasuresForPurpose")
    @ResponseWrapper(localName = "GetMeasuresForPurposeResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetMeasuresForPurposeResponse")
    public ArrayOfMeasure getMeasuresForPurpose(
        @WebParam(name = "purpose", targetNamespace = "http://ella.ledningskollen.se/")
        Purpose purpose);

    /**
     * Please do not use this method, it only works for Ledningsägarmodul.
     * 
     * @param recipients
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfCase
     */
    @WebMethod(operationName = "GetNewCases", action = "http://ella.ledningskollen.se/GetNewCases")
    @WebResult(name = "GetNewCasesResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetNewCases", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetNewCases")
    @ResponseWrapper(localName = "GetNewCasesResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetNewCasesResponse")
    public ArrayOfCase getNewCases(
        @WebParam(name = "recipients", targetNamespace = "http://ella.ledningskollen.se/")
        ArrayOfRecipient recipients);

    /**
     * Please do not use this method, it only works for Ledningsägarmodul.
     * 
     * @param recipients
     * @return
     *     returns se.ledningskollen.api.cableowner.ArrayOfCase
     */
    @WebMethod(operationName = "GetNewCanceledCases", action = "http://ella.ledningskollen.se/GetNewCanceledCases")
    @WebResult(name = "GetNewCanceledCasesResult", targetNamespace = "http://ella.ledningskollen.se/")
    @RequestWrapper(localName = "GetNewCanceledCases", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetNewCanceledCases")
    @ResponseWrapper(localName = "GetNewCanceledCasesResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.GetNewCanceledCasesResponse")
    public ArrayOfCase getNewCanceledCases(
        @WebParam(name = "recipients", targetNamespace = "http://ella.ledningskollen.se/")
        ArrayOfRecipient recipients);

    /**
     * Please do not use this method, it only works for Ledningsägarmodul.
     * 
     * @param caseNumber
     */
    @WebMethod(operationName = "SetCanceledCaseAsFetched", action = "http://ella.ledningskollen.se/SetCanceledCaseAsFetched")
    @RequestWrapper(localName = "SetCanceledCaseAsFetched", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.SetCanceledCaseAsFetched")
    @ResponseWrapper(localName = "SetCanceledCaseAsFetchedResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.SetCanceledCaseAsFetchedResponse")
    public void setCanceledCaseAsFetched(
        @WebParam(name = "caseNumber", targetNamespace = "http://ella.ledningskollen.se/")
        String caseNumber);

    /**
     * Please do not use this method, it only works for Ledningsägarmodul. Sets the case for your organization to Inga intressen.
     * 
     * @param caseNumber
     */
    @WebMethod(operationName = "CaseNoInterest", action = "http://ella.ledningskollen.se/CaseNoInterest")
    @RequestWrapper(localName = "CaseNoInterest", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.CaseNoInterest")
    @ResponseWrapper(localName = "CaseNoInterestResponse", targetNamespace = "http://ella.ledningskollen.se/", className = "se.ledningskollen.api.cableowner.CaseNoInterestResponse")
    public void caseNoInterest(
        @WebParam(name = "caseNumber", targetNamespace = "http://ella.ledningskollen.se/")
        String caseNumber);

}
